title: SkyPulse
email: bindsch@mpi-sws.org
author: SkyPulse Project Team
copyright: "Copyright © 2024 SkyPulse Project"
description: >- 
  Unlock the Potential of Satellite Data by Combining It With Any Other Data Source

baseurl: ""
url: "https://sky-pulse.github.io"

# No theme - custom layout

# Build settings
markdown: kramdown

# Basic plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/